# Generated by Django 4.2.7 on 2024-01-02 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_bank_user_bank_username"),
        ("accessing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
