# Generated by Django 4.2.7 on 2024-01-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accessing", "0001_initial"),
        ("myapp", "0003_delete_placetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="accessing.userprofile",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
