# Generated by Django 4.2.7 on 2024-01-02 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
