# Generated by Django 4.2.7 on 2024-01-03 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankevent",
            name="time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
