# Generated by Django 4.2.7 on 2024-01-11 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_savings_investments_income"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Investments",
        ),
    ]
