# Generated by Django 4.2.7 on 2024-01-13 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_income"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Investments",
            new_name="Investment",
        ),
        migrations.RenameModel(
            old_name="Savings",
            new_name="Saving",
        ),
    ]
