# Generated by Django 4.2.7 on 2024-01-19 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_alter_income_amount1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="balance",
        ),
    ]
