# Generated by Django 4.2.7 on 2024-01-02 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_bankevent_place_alter_bankevent_place_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlaceType",
        ),
    ]
