# Generated by Django 4.2.7 on 2024-01-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_bank_user_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="user",
        ),
        migrations.AddField(
            model_name="bank",
            name="username",
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
