# Generated by Django 4.2.7 on 2024-01-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_bankevent_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankevent",
            name="place_type",
            field=models.CharField(
                choices=[
                    ("Groceries", "Groceries"),
                    ("Restaurants", "Restaurants"),
                    ("Cafe", "Cafe"),
                    ("Hobby", "Hobby"),
                    ("Travel", "Travel"),
                    ("Culture", "Culture"),
                    ("Clothing", "Clothing"),
                    ("Subscriptions", "Subscriptions"),
                    ("Telephone, Internet, TV", "Telephone, Internet, TV"),
                    ("Household costs", "Household costs"),
                    ("Household", "Household"),
                    ("Car", "Car"),
                    ("Insurance", "Insurance"),
                    ("Credit card", "Cradit card"),
                    ("Loan", "Loan"),
                    ("Healthcare", "Healthcare"),
                    ("Child", "Child"),
                    ("People", "People"),
                    ("Presents", "Presents"),
                    ("Investments", "Investments"),
                    ("Savings", "Savings"),
                    ("Charity", "Charity"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
