# Generated by Django 4.2.7 on 2024-01-13 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_investments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Income",
        ),
    ]
