# Generated by Django 4.2.7 on 2024-01-13 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_rename_amount_income_amount1_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Investment",
        ),
    ]
