# Generated by Django 4.2.7 on 2024-01-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_delete_investment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place3", models.CharField(max_length=100)),
                ("amount3", models.DecimalField(decimal_places=2, max_digits=20)),
                ("interest", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "bank_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bank"
                    ),
                ),
            ],
        ),
    ]
