# Generated by Django 4.2.7 on 2024-01-16 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_alter_income_amount1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount1",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
