# Generated by Django 4.2.7 on 2024-02-29 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_remove_bank_balance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankevent",
            old_name="amount",
            new_name="bankevent_amount",
        ),
        migrations.RenameField(
            model_name="bankevent",
            old_name="place",
            new_name="bankevent_place",
        ),
        migrations.RenameField(
            model_name="bankevent",
            old_name="place_type",
            new_name="bankevent_place_type",
        ),
        migrations.RenameField(
            model_name="bankevent",
            old_name="time",
            new_name="bankevent_time",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="amount1",
            new_name="income_amount",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="place1",
            new_name="income_place",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="wageday",
            new_name="income_wageday",
        ),
        migrations.RenameField(
            model_name="investment",
            old_name="amount3",
            new_name="investment_amount",
        ),
        migrations.RenameField(
            model_name="saving",
            old_name="amount2",
            new_name="saving_amount",
        ),
        migrations.CreateModel(
            name="Subscribtion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscribtion_place", models.CharField(max_length=100)),
                (
                    "subscribtion_place_type",
                    models.CharField(
                        choices=[
                            ("Groceries", "Groceries"),
                            ("Restaurants", "Restaurants"),
                            ("Cafe", "Cafe"),
                            ("Hobby", "Hobby"),
                            ("Travel", "Travel"),
                            ("Culture", "Culture"),
                            ("Clothing", "Clothing"),
                            ("Subscriptions", "Subscriptions"),
                            ("Telephone, Internet, TV", "Telephone, Internet, TV"),
                            ("Household costs", "Household costs"),
                            ("Household", "Household"),
                            ("Car", "Car"),
                            ("Insurance", "Insurance"),
                            ("Credit card", "Cradit card"),
                            ("Loan", "Loan"),
                            ("Healthcare", "Healthcare"),
                            ("Child", "Child"),
                            ("People", "People"),
                            ("Presents", "Presents"),
                            ("Investments", "Investments"),
                            ("Savings", "Savings"),
                            ("Charity", "Charity"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "subscribtion_repetition",
                    models.IntegerField(
                        choices=[
                            (1, "Daily"),
                            (7, "Weekly"),
                            (30, "Monthly"),
                            (365, "Yearly"),
                        ]
                    ),
                ),
                (
                    "subscribtion_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "bank_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bank"
                    ),
                ),
            ],
        ),
    ]
