# Generated by Django 4.2.7 on 2024-02-29 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0023_rename_amount_bankevent_bankevent_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankevent",
            old_name="bankevent_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="bankevent",
            old_name="bank_id",
            new_name="bank",
        ),
        migrations.RenameField(
            model_name="bankevent",
            old_name="bankevent_place",
            new_name="place",
        ),
        migrations.RenameField(
            model_name="bankevent",
            old_name="bankevent_place_type",
            new_name="place_type",
        ),
        migrations.RenameField(
            model_name="bankevent",
            old_name="bankevent_time",
            new_name="time",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="income_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="bank_id",
            new_name="bank",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="income_place",
            new_name="place",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="income_wageday",
            new_name="wageday",
        ),
        migrations.RenameField(
            model_name="investment",
            old_name="investment_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="investment",
            old_name="bank_id",
            new_name="bank",
        ),
        migrations.RenameField(
            model_name="saving",
            old_name="saving_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="saving",
            old_name="bank_id",
            new_name="bank",
        ),
        migrations.RenameField(
            model_name="subscribtion",
            old_name="subscribtion_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="subscribtion",
            old_name="subscribtion_place",
            new_name="place",
        ),
        migrations.RenameField(
            model_name="subscribtion",
            old_name="subscribtion_place_type",
            new_name="place_type",
        ),
        migrations.RenameField(
            model_name="subscribtion",
            old_name="subscribtion_repetition",
            new_name="repetition",
        ),
    ]
