# Generated by Django 4.2.7 on 2024-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0024_rename_bankevent_amount_bankevent_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="amount",
        ),
        migrations.AddField(
            model_name="investment",
            name="key",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
