# Generated by Django 4.2.7 on 2024-04-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0025_remove_investment_amount_investment_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
