# Generated by Django 4.2.7 on 2024-05-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0026_bank_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="wage_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="wageday",
            field=models.DateField(),
        ),
    ]
