# Generated by Django 4.2.7 on 2024-05-01 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0027_income_wage_date_alter_income_wageday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="wage_date",
        ),
        migrations.AlterField(
            model_name="income",
            name="wageday",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ]
            ),
        ),
    ]
