# Generated by Django 4.2.7 on 2024-05-03 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0028_remove_income_wage_date_alter_income_wageday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="wageday",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(limit_value=1),
                    django.core.validators.MaxValueValidator(limit_value=31),
                ]
            ),
        ),
    ]
